[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["bash build-railway.sh"]

[start]
cmd = "npx prisma db push --skip-generate && node prisma/seed.ts && node .next/standalone/server.js"
